services:
  arcane:
    image:ghcr.io/ofkm/arcane:latest
    container_name:arcane
    user:root
    ports:
      -'23000:3000'
    volumes:
      -/var/run/docker.sock:/var/run/docker.sock
      -arcane-data:/app/data
    environment:
      -APP_ENV=production
      -DOCKER_GID=999
      -PUBLIC_SESSION_SECRET=RXdz9PsfCPKgPPSn+j2z2lzTYDep9fdODP9SPeWpQ2g=
    restart:unless-stopped

volumes:
arcane-data:
    driver:local